version: "3.7"

services:
  product_database:
    image: mariadb
    container_name: product_database
    restart: always
    ports:
      - ${MARIADB_PORT}:${MARIADB_PORT}
    environment:
      MARIADB_ROOT_USER: ${MARIADB_ROOT_USER}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_ROOT_HOST: ${MARIADB_ROOT_HOST}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    networks:
      - pedidopago

  product_microservice:
    image: node:latest
    container_name: product_microservice
    restart: always
    env_file:
      - .env
    depends_on:
      - product_database
    ports:
      - ${GRPC_PRODUCT_SERVER_PORT}:${GRPC_PRODUCT_SERVER_PORT}
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    command: yarn dev
    networks:
      - pedidopago

networks:
  pedidopago:
    name: pedidopago
    driver: bridge