version: '3.7'

services:
  product-database:
    image: mariadb
    container_name: product-database
    restart: always
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    environment:
      MARIADB_ROOT_USER: ${DATABASE_ROOT_USER}
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_ROOT_HOST: ${DATABASE_ROOT_HOST}
      MARIADB_USER: ${DATABASE_USER}
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_DATABASE}
    networks:
      - product-networks

  product-microservice:
    image: node:latest
    container_name: product-microservice
    restart: always
    environment:
      GRPC_PRODUCT_SERVER_HOST: ${GRPC_PRODUCT_SERVER_HOST}
    depends_on:
      - product-database
    ports:
      - ${GRPC_PRODUCT_SERVER_PORT}:${GRPC_PRODUCT_SERVER_PORT}
    working_dir: /usr/app
    volumes:
      - .:/usr/app
    command: yarn dev
    networks:
      - product-networks

networks:
  product-networks:
    name: product-networks
    driver: bridge
